### ISSUE TITLE
支払いの具体的な方法やプロセスを決定する

### ISSUE THREAD

**Issue by How2HideYou** [nintc-al2020-4/electronic-payment-front#1]
- 金額を入力するのは客側か店側の端末か？
- そもそもQRコードを提示するのは客側か店側か？
  - 店側が提示した方がおそらく安全
- 支払い完了はどのように検出するか？
- 開発コストも考慮

QRコードのフォーマットはこれが決まってから検討する。

**Comment by How2HideYou** [comment]
何かアイデアや提案があれば書き込んでください。

**Comment by Crow314** [comment]
そもそも、要件は **APIから返ってくるトークンをQRコードとして表示する** だったので、フォーマットを考える必要があるかは疑問ですが、以下の通りかなと

- QRコードを提示するのは一般ユーザー側
  - Webアプリにカメラ読み込み機能を実装するのは困難
- 店側が金額を入力する
  - 店側は読み込んだトークンと金額をAPIに送信する流れです
- 支払い完了の検出は実装しない
  - 画面の作成など必要工数が大きい
  - やる気を出せばWebSocket辺りで実装できなくもないが、使う技術がかなり異なる

**Comment by How2HideYou** [comment]
それで、どうやってAPIからトークンを取得するのですか？（質問ばかりですみません...）
おそらくGETメソッドを使うのだと思いますが、どこにどういう内容を送信すればいいのかなどの情報が全くありません。

**Comment by How2HideYou** [comment]
https://github.com/nintc-al2020-4/electronic-payment-api/search?q=token
APIのリポジトリを検索したらサーバー側でそれっぽいことをするコードがいくつか見つかりましたが、Rubyの知識がゼロなので結局どうすればいいか分かりません。

**Comment by Crow314** [comment]
https://github.com/nintc-al2020-4/electronic-payment-api/blob/develop/README.md

## 支払いトークン [/payment_token]

### トークン取得 [GET]

+ Request
  + Headers
    ```text
    Authorization: Token xxxx
    ```

+ Responce 200 (application/json)
  + Body
    ```json
    {
      "token": "Base64"
    }
    ```

+ Responce 401 (application/json)
  + Body
    ```json
    {
      "error": "Invalid token"
    }
    ```
