### ISSUE TITLE
position of require

### ISSUE THREAD

**Issue by Akatsuki1910** [nintc-al2020-4/electronic-payment-front#3]
requireを関数の中に書かない方がいいと思います。
https://github.com/nintc-al2020-4/electronic-payment-front/blob/b9776213debe30c35eee5657b834f9442e6d5d57/src/components/pages/Charge.vue#L66

**Comment by Crow314** [comment]
Fixed it
Thanks

https://github.com/nintc-al2020-4/electronic-payment-front/commit/33c24904cdacc55344a1e4b2e31176c40863e042
