### ISSUE TITLE
router link

### ISSUE THREAD

**Issue by Akatsuki1910** [nintc-al2020-4/electronic-payment-front#4]
ページ遷移はrouter-linkタグを使用する方がいいと思います。
https://router.vuejs.org/ja/api/#router-link

https://github.com/nintc-al2020-4/electronic-payment-front/blob/b9776213debe30c35eee5657b834f9442e6d5d57/src/components/pages/Pay.vue#L7

**Comment by Akatsuki1910** [comment]
他にもありますが参考までに。
https://github.com/nintc-al2020-4/electronic-payment-front/blob/555c6f6f2cb2dfbb839c55479cc3938e49f381ed/src/components/modules/Header.vue#L4
https://github.com/nintc-al2020-4/electronic-payment-front/blob/555c6f6f2cb2dfbb839c55479cc3938e49f381ed/src/components/modules/Header.vue#L10~#L12

**Comment by Crow314** [comment]
Fix it
Thanks!
