### ISSUE TITLE
改行コードによるコンパイルエラー

### ISSUE THREAD

**Issue by How2HideYou** [nintc-al2020-4/electronic-payment-front#7]
pullしてサーバをスタートさせようとすると、次のようなエラーが大量に出てきました。
```
   1:11   error  Delete `␍`  prettier/prettier
   2:20   error  Delete `␍`  prettier/prettier
   3:30   error  Delete `␍`  prettier/prettier
   4:12   error  Delete `␍`  prettier/prettier
   ...
```
Windowsの改行コードはCR+LFですが、LinuxではLFだけです。どうやらCRがあるためにエラーを吐いていると思われます。
コードを修正するのは難しいと思いますので、設定などでCR+LFを正しく認識させてコンパイルを通す方法はありませんか？

**Comment by Crow314** [comment]
コードフォーマットを統一する目的で敢えてエラーを吐かせています
私の知る限り、開発においてはWindowsであろうがLFで統一することが一般的かとは思います

そもそも予めこれをやっていればLFで統一されるかと思うのですが
(厳密には自身が最初に作成した場合CRLFが残り得ますが)
https://github.com/nintc-al2020-4/electronic-payment-front/blame/develop/README.md#L15

リモート(GitHub)側ではLFで統一してあるので、エディタなどの一括変更機能を使用するか、クローンし直すかでローカル側もLFで統一できます
https://qiita.com/tanakahisateru/items/1c9ddf8d33d6727269ec
https://qiita.com/June8715/items/24307ee467baee51387e

なお、1ファイルだけCRLFでリポジトリに上がっていた分は同時にLFへ修正しています
https://github.com/nintc-al2020-4/electronic-payment-front/commit/55a468b08c295b1116e31469b968de29bbf01769#diff-66ee14bbb148d3e209caeb78444cb4d265e6e3dc28077f8d23fc36571c99db7bR1
